# Generated by Django 4.1.1 on 2022-10-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0002_alter_cat_options_alter_dog_options_cat_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="adopted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cat",
            name="weight",
            field=models.IntegerField(default=5),
        ),
    ]
